/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkomm
 */
public class PembelianBarang extends javax.swing.JFrame {

    /**
     * Creates new form PembelianBarang
     */
    public PembelianBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JB = new javax.swing.JTextField();
        KB = new javax.swing.JTextField();
        HB = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pembelian Barang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(159, 20, 140, 20);

        jLabel2.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 84, 120, 20);

        jLabel3.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 120, 30);

        jLabel4.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 120, 30);
        getContentPane().add(JB);
        JB.setBounds(200, 160, 130, 30);
        getContentPane().add(KB);
        KB.setBounds(200, 80, 130, 30);
        getContentPane().add(HB);
        HB.setBounds(200, 120, 130, 30);

        btnTambah.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        getContentPane().add(btnTambah);
        btnTambah.setBounds(40, 220, 100, 23);

        btnOK.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("Ok");
        getContentPane().add(btnOK);
        btnOK.setBounds(130, 220, 70, 23);

        btnCancel.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(200, 220, 90, 23);

        btnMember.setFont(new java.awt.Font("DFPOP1-W9", 1, 14)); // NOI18N
        btnMember.setForeground(new java.awt.Color(255, 255, 255));
        btnMember.setText("Member");
        getContentPane().add(btnMember);
        btnMember.setBounds(290, 220, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembelianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembelianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembelianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembelianBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembelianBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HB;
    private javax.swing.JTextField JB;
    private javax.swing.JTextField KB;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
